Joshua/flutter versions
CircleCI-Public/flutter-orb pull request #15
Opened 2022-07-01 06:44 UTC by joshuadeguzman

**SEMVER Update Type:**
- [ ] Major
- [X] Minor
- [ ] Patch

## Description:

The [docs](https://circleci.com/developer/orbs/orb/circleci/flutter#usage-install_for_macos) for this orb is a bit outdated and might confused newcomers trying out this orb, for example, the version parameter issues.

I fixed the `version` requirement and make use of `flutter_version` wherever the Flutter SDK needs to be set.

Next, changed the usage examples with the updated parameters and missing checkout (causes cache key issues).

Last, I updated the default version to the latest stable [Flutter SDK release](https://docs.flutter.dev/development/tools/sdk/releases?tab=macos), including the sample app working on the latest SDK.

## Motivation:

- Closes #14
- Closes #13
- Closes #8

## Checklist:

- [X] All new jobs, commands, executors, parameters have descriptions.
- [X] Usage Example version numbers have been updated.
- [X] Changelog has been updated.

2022-07-01 11:48 UTC, joshuadeguzman commented
Hey guys, would you be able to take a look at this? @tadashi0713

2023-01-31 17:42 UTC, JalexChen commented
hey @joshuadeguzman - thank you for putting this PR in. at first glance, this looks alright, but we are holding off on releasing any orb updates at the moment. will revisit this in a bit and let the job run

2023-02-15 19:15 UTC, JalexChen commented
hi @joshuadeguzman - do you mind rebasing this on main so we can consolidate and squash commits?

2023-02-15 19:53 UTC, JalexChen requested changes
again, thank you for the contribution. i would update the PR again with the latest versions if you so choose, but i only ask that you rebase it. 

if you don't update the versions, don't worry we can do that in a separate PR, however, the change in parameter naming is necessary

2023-02-15 19:53 UTC, JalexChen commented on src/jobs/lint.yml
> +  flutter-version:
you will need to change line 17 to be `flutter-version` instead of `version`

2023-02-15 19:53 UTC, JalexChen commented on src/jobs/unit_test.yml
> +  flutter-version:
you will need to change line 17 to be `flutter-version`

2023-02-15 19:53 UTC, JalexChen commented on src/commands/install_sdk.yml
> +  flutter-version:
replace all `<<parameters.version>>` with `<<parameters.flutter-version>>`

2023-02-22 20:59 UTC, JalexChen commented
Closing this out as the changes made would need to be added with @joshuadeguzman accepting any PRs. Instead, a lot of the changes here are now in PR #23 so that he still gets contributor credit

2023-02-22 20:59 UTC, closed without merging